name: Hello World CI/CD Use artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create timestamped file
        run: |
          echo "Hello, CI/CD World! Created at $(date)" > timestamped_hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-artifact
          path: timestamped_hello.txt

  use-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hello-artifact
      - name: Display artifact contents
        run: cat timestamped_hello.txt